@startuml RobotBase::generalSearchRun()
start
:calibration();
:startDequeue();
repeat
    :reached = calcNextDirections();
    :queueNextDirections();
    :break if reached;
    :waitForEndAction();
    :senseWalls();
    :updateWalls();
    :findNextDirection();
    :queueNextDirection();
repeat while (true)
:queueAction(ST_HALF_STOP);
:queueAction(START_INIT);
end
@enduml
